### PR TITLE
Show multiple folios

### PR DESCRIPTION
**Pull request by paltman**
- there is still a CSS issue because subsequent folios are inching their way up above their container

### CODE REVIEW

**Comment by jacobwegner** [comment]
(I fixed up the Netlify mapping just to make it easier to see the preview e.g. https://deploy-preview-37--scaife-viewer-frontend.netlify.app/explore-homer?urn=urn%3Acts%3AgreekLit%3Atlg0012.tlg001.msA-folios%3A12r-12v)

**Review by jacobwegner — CHANGES_REQUESTED** [review]
@paltman I just did a QA pass via:

https://deploy-preview-37--scaife-viewer-frontend.netlify.app/explore-homer?urn=urn%3Acts%3AgreekLit%3Atlg0012.tlg001.msA-folios%3A12r-13v

The "toolbar" controls for open sea dragon only impact the first instance.

Steps to reproduce:

- Scroll down to the second folio image
- Try to zoom in / out using the toolbar
- Nothing happens on the second folio image, but if you scroll to the first one, the zooming did apply

**Comment by paltman** [comment]
@jacobwegner fixed

**Review by jacobwegner — APPROVED** [review]
LGTM

**Pull request merged**
