### PR TITLE
Merge Alignment Modes

### PR DESCRIPTION
**Pull request by paltman**

### CODE REVIEW

**Comment by jacobwegner** [comment]
@paltman: In caeb75c, I moved away from `items` and rebuilt its contents solely from tokens within the frontend.

I think it is enough to satisfy [sv-mini/#35](https://github.com/scaife-viewer/sv-mini/issues/35), but I'll follow up with a schema change for ATLAS that will change some of the queries we're using in [sv-mini/#38](https://github.com/scaife-viewer/sv-mini/issues/38)

**Comment by jacobwegner** [comment]
(in the future when we handle intra-text alignment or three column alignments, we'll likely move away from "left" and "right" and rely on 0-based position of the relations)

**Comment by jacobwegner** [comment]
So selecting "Iliad Sentence Alignment" in 

https://one-true-alignments-mode--scaife-viewer-frontend.netlify.app/explore-homer?urn=urn%3Acts%3AgreekLit%3Atlg0012.tlg001.perseus-grc2%3A1.1-1.10

should operate similar to "Sentence Alignments" in:

https://token-alignments-mode--scaife-viewer-frontend.netlify.app/explore-homer?urn=urn%3Acts%3AgreekLit%3Atlg0012.tlg001.perseus-grc2%3A1.1-1.10

**Comment by paltman** [comment]
@jacobwegner it actually works better than "Sentence Alignments" as the references are correct. :)

**Review by jacobwegner — APPROVED** [review]
Approved by the team

**Pull request merged**
